### ISSUE TITLE
Rearm blacklist in different languages

### ISSUE THREAD

**Issue by rlnt** [oiad/service_points#2]
Currently there is a problem with the blacklist for the weapons that should not be able to be rearmed.

As an example: The english word "horn" is "Hupe" in German.
So if you blacklist the horn in the config, you will still be able to rearm the horn if you play ArmA in German language.

`			_gWeaponName = getText (configFile >> "CfgWeapons" >> _x >> "displayName");
			if !(_gWeaponName in _rearm_ignore) then {
				_gWeapons set [count _gWeapons, [_x,_gWeaponName,_gTurret]];
			}; 
`

This code checks for the display name and then excludes this item from the rearm option. I don't know whether you are able to check for the stringtable in sqf so it scans this word in all languages, but that would prevent this option. I mean another solution is to add the word in all languages in the blacklist but that's a bit complicated and too much work.
Maybe you could also use the classname instead of the displayname but my knowledge is not enough to suggest a change.

**Comment by oiad** [comment]
I like how the service points script has always gone by display name instead of classname, since getting the ACTUAL class name of the weapon (i.e sidewinderblahblahmissles) is hard unless you have a script.

It's not hard for people to edit the _rearm_ignore array to their liking, no different from any other script changing languages around/variables around.

For the moment, i'm not too bothered by the issue as I think 80% of people using this would be english or understand it atleast enough to change it but thankyou for atleast bringing it up.
